default_agent: eden_greenhouse_agent
agents:
  eden_greenhouse_agent:
    name: eden_greenhouse_agent
    language: python
    node_version: '20'
    entrypoint: /Users/btr-dev/Documents/informatik/astrofarm/eden/runtime_entry.py
    deployment_type: direct_code_deploy
    runtime_type: PYTHON_3_11
    platform: linux/arm64
    container_runtime: null
    source_path: /Users/btr-dev/Documents/informatik/astrofarm
    aws:
      execution_role: arn:aws:iam::658707946640:role/eden-runtime-agentcore-role-48c23c3
      execution_role_auto_create: true
      account: '658707946640'
      region: us-west-2
      ecr_repository: null
      ecr_auto_create: false
      s3_path: s3://bedrock-agentcore-codebuild-sources-658707946640-us-west-2
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: 900
        max_lifetime: 28800
    bedrock_agentcore:
      agent_id: eden_greenhouse_agent-7JukviH1up
      agent_arn: arn:aws:bedrock-agentcore:us-west-2:658707946640:runtime/eden_greenhouse_agent-7JukviH1up
      agent_session_id: 78b93f62-7a83-4621-8938-633511b5f6ef
    codebuild:
      project_name: null
      execution_role: null
      source_bucket: null
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
